data:
  runtime_json_name: 2025-07-16_18-25__ReferenceTrajectory_StaticPolyhedronConstraints_0
  ros_rec_json_name: 2025-07-16_sim_falcon_hmpc_no_dist_K_no_meas_noise_L
  # t: 2.5
  # t: 3
  t: 6

plot_settings:
  r_tmpc_ref: 0.0003
  r_tmpc: 0.0002
  r_x0: 0.0002
  r_x: 0.0001
