data:
  # runtime_json_name: 2025-07-16_18-25__ReferenceTrajectory_StaticPolyhedronConstraints_0
  # ros_rec_json_name: 2025-07-16_sim_falcon_hmpc_no_dist_K_no_meas_noise_L
  # ros_rec_json_name: 2025-07-17_sim_falcon_hmpc_no_dist_K_no_meas_noise_L
  # ros_rec_json_name: 2025-07-17_sim_falcon_hmpc_Qpos10_no_dist_K_no_meas_noise_L
  # ros_rec_json_name: 2025-07-17_sim_falcon_hmpc_Q1000eye_R1000eye_no_dist_K_no_meas_noise_L
  # ros_rec_json_name: 2025-07-18_sim_falcon_hmpc_R1000eye_no_dist_K_no_meas_noise_L
  # runtime_json_name: 2025-07-29_18-54__ReferenceTrajectory_StaticPolyhedronConstraints_0
  # ros_rec_json_name: 2025-07-29_gaz_meas_noise_falcon_check_tmpc_cost_rohmpc
  # runtime_json_name: 2025-07-30_11-57__ReferenceTrajectory_StaticPolyhedronConstraints_0
  # ros_rec_json_name: 2025-07-29_gaz_meas_noise_falcon_-1_-1_to_0_0
  # runtime_json_name: 2025-07-31_09-57__ReferenceTrajectory_StaticPolyhedronConstraints_0
  # ros_rec_json_name: 2025-07-31_gaz_meas_noise_falcon_-1_-1_to_0_0
  # runtime_json_name: 2025-07-31_14-43__ReferenceTrajectory_StaticPolyhedronConstraints_0
  # ros_rec_json_name: 2025-07-31_gaz_meas_noise_falcon_-1dot5_-0dot5_to_-0dot5_-0dot5
  # runtime_json_name: 2025-08-03_15-30__ReferenceTrajectory_StaticPolyhedronConstraints_0
  # ros_rec_json_name: 2025-08-03_gaz_meas_noise_falcon_-1dot5_-0dot5_to_-0dot5_-0dot5
  runtime_json_name: 2025-08-05_06-00__ReferenceTrajectory_StaticPolyhedronConstraints_0
  ros_rec_json_name: 2025-08-04_gaz_meas_noise_falcon_-1dot5_-0dot5_to_-0dot5_-0dot5

print_settings:
  # t: -1
  t: 3
  check_gt_est_states: False
  print_pobj_comp: False
  # print_track_err: ["total", "u", "x", "p", "2d_p"]
  print_track_err: []

do_plot:
  obs: False
  obs_inflation: True
  pmpc_tube: True
  pmpc_pred: True
  tmpc_ref: False
  tmpc_tube: True
  tmpc_pred: False
  x: True

plot_settings:
  t: [1, 4]
  k_pmpc_pred: [0]
  k_ref: [0]
  k_pred: [0]
  t_div_tmpc_tube: 20
  linewidth_pmpc_tube: 1
  linewidth_tmpc_tube: 1
  grid_resolution: 0.0005 # needs to be the same value as specified in the map used by the occupancy grid creator
  r_pmpc: 0.0012
  r_tmpc_ref: 0.0009
  r_tmpc: 0.0006
  r_x: 0.0003
  alpha_tmpc_tube_controller: 0.7
  alpha_tmpc_tube_total: 0.4
