data:
  runtime_json_name: 2025-07-16_18-25__ReferenceTrajectory_StaticPolyhedronConstraints_0
  # ros_rec_json_name: 2025-07-16_sim_falcon_hmpc_no_dist_K_no_meas_noise_L
  # ros_rec_json_name: 2025-07-17_sim_falcon_hmpc_no_dist_K_no_meas_noise_L
  # ros_rec_json_name: 2025-07-17_sim_falcon_hmpc_Qpos10_no_dist_K_no_meas_noise_L
  # ros_rec_json_name: 2025-07-17_sim_falcon_hmpc_Q1000eye_R1000eye_no_dist_K_no_meas_noise_L
  ros_rec_json_name: 2025-07-18_sim_falcon_hmpc_R1000eye_no_dist_K_no_meas_noise_L
  t: -1
  t: 2.5
  t: 3
  t: 6

print_settings:
  print_pobj_comp: True
  print_track_err: ["total", "u", "x", "p", "2d_p"]

plot_settings:
  r_tmpc_ref: 0.0003
  r_tmpc: 0.0002
  r_x0: 0.0002
  r_x: 0.0001
